###
GET http://localhost:3000

###
GET http://localhost:3000/alunos

###
POST http://localhost:3000/alunos/cadastro
content-type: application/json

{
    "matricula": "121313",
    "nome": "Joel Santos",
    "email": "teste@emial.com",
    "turma": "B",
    "serie": 3,
    "sexo": "M",
    "telefone": "(84) 90909090",
    "endereco": "Rua teste do teste",
    "responsavel": "Natalina"

}
###
GET http://localhost:3000/alunos/listarAlunos
###
GET http://localhost:3000/alunos/buscarAluno/12345

###
PUT http://localhost:3000/alunos/editarAluno/12345
content-type: application/json

{
    "nome": "Natalina",
    "email": "natalina@emial.com",
    "turma": "D",
    "serie": 2,
    "sexo": "F",
    "telefone": "(84) 90909090",
    "endereco": "Rua das renas do Natal, 25",
    "responsavel": "Papai Noel"

}

###

DELETE  http://localhost:3000/alunos/deletarAluno/12345